name: Deploy to Cloudflare Workers
on:
  push:
    branches:
        - master
  pull_request:
  repository_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Publish Worker
        uses: cloudflare/wrangler-action@1.2.0
        with:
          workingDirectory: hello
          apiToken: ${{ secrets.CF_API_TOKEN }}
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}        